# Unset/Set CFLAGS for sanity checks and debugging 
#CFLAGS = -Wpedantic -Wall -g -DDEBUG
CFLAGS = -Wall -Wpedantic -std=c99
LIBS = -lm
CC = gcc
BUILDDIR = ~/Documents/SeniorDesign/QuadSovler

IO.o:	IO.c IO.h	

clean:
	rm *.o
